import React, { useState } from "react";
import Image from "next/image";
import CoverThumbnails from "../components/CoverThumbnails";
import ProductList from "../components/ProductList";
import BottomCart from "../components/BottomCart";
import Cart from "../components/Cart";
import { Urls } from "../configs/configs";

// const products_result = [
//   {
//     id_product: "1",
//     id_supplier: "1",
//     id_manufacturer: "1",
//     id_category_default: "4",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 0,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "22,94 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_1",
//     supplier_reference: "demo_1_46",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "2",
//     uploadable_files: "0",
//     text_fields: "1",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:28",
//     date_upd: "2022-08-01 15:08:38",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p><span></span><span></span><span style=\"white-space:pre-wrap;\">Mon papa chou, ma fille adorée ! Quel lien incroyable que celui qui unit un père et sa fille ! Un livre plein d'humour et de légèreté à remplir rien qu'à deux pour profiter de cette relation si particulière. Que l'on consomme une page par jour ou toutes d'un coup, père et fille sont certains de partager un moment de complicité !<br /><br />Une belle idée cadeau pour la fête des pères, le Noël d'un papa...<br /><br />Format : 15 x 21 cm, 60 pages<br /><br />Couverture : souple<br /><br />Couleur : Quadrichromie et un beau corail pantone<br /><br />Âge : à partir de 6 ans<br /><br />Ce livre à remplir est imprimé dans le Nord de la France. Votre commande est ensuite préparée avec amour dans un ESAT (atelier protégé) par des travailleurs handicapés. Un partenariat qui met du sens dans notre entreprise Minus.<br /><br />Minus Editions imagine des livres et des jeux qui créent du lien entre les enfants et leurs parents.<br /></span></p>",
//     description_short:
//       '<ul>\r\n<li><span style="white-space:pre-wrap;">22 œuvres majeures de l\'Histoire de l\'Art</span></li>\r\n<li><span style="white-space:pre-wrap;">3 façons de jouer pour alterner le plaisir d\'apprendre</span></li>\r\n<li><span style="white-space:pre-wrap;">Une façon ludique d\'apprendre les bases de l\'Art</span></li>\r\n<li><span style="white-space:pre-wrap;">À partir de 5 ans pour jouer en famille</span></li>\r\n<li><span style="white-space:pre-wrap;">Avec un livret explicatif pour en savoir plus sur les œuvres et les artistes</span></li>\r\n</ul>',
//     link_rewrite: "hummingbird-printed-t-shirt",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "T-shirt imprimé colibri",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "1-1",
//     legend: "T-shirt imprimé colibri",
//     manufacturer_name: "Studio Design",
//     category_default: "Hommes",
//     orderprice: "23.900000",
//     allow_oosp: 0,
//     cover_image_id: "1",
//     category: "hommes",
//     category_name: "Hommes",
//     link: "http://localhost/prestaboutique/hommes/1-hummingbird-printed-t-shirt.html",
//     attribute_price: 0,
//     price_tax_exc: 19.12,
//     price_without_reduction: 28.68,
//     price_without_reduction_without_tax: 23.9,
//     reduction: 5.736,
//     reduction_without_tax: 4.78,
//     specific_prices: {
//       id_specific_price: "1",
//       id_specific_price_rule: "0",
//       id_cart: "0",
//       id_product: "1",
//       id_shop: "0",
//       id_shop_group: "0",
//       id_currency: "0",
//       id_country: "0",
//       id_group: "0",
//       id_customer: "0",
//       id_product_attribute: "0",
//       price: "-1.000000",
//       from_quantity: "1",
//       reduction: "0.200000",
//       reduction_tax: "1",
//       reduction_type: "percentage",
//       from: "0000-00-00 00:00:00",
//       to: "0000-00-00 00:00:00",
//       score: "32",
//     },
//     quantity_all_versions: 0,
//     features: [
//       {
//         name: "Composition",
//         value: "Coton",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "Manches courtes",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: true,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/1-home_default/hummingbird-printed-t-shirt.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/1-home_default/hummingbird-printed-t-shirt.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: true,
//     discount_type: "percentage",
//     discount_percentage: "-20%",
//     discount_percentage_absolute: "20%",
//     discount_amount: "5,74 €",
//     discount_amount_to_display: "-5,74 €",
//     price_amount: 22.94,
//     regular_price_amount: 28.68,
//     regular_price: "28,68 €",
//     discount_to_display: "5,74 €",
//     unit_price_full: "",
//     show_availability: true,
//     availability_message: "Rupture de stock",
//     availability_date: null,
//     availability: "unavailable",
//   },
//   {
//     id_product: "2",
//     id_supplier: "1",
//     id_manufacturer: "1",
//     id_category_default: "5",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 1200,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "34,46 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_3",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "404",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "9",
//     date_add: "2022-05-28 02:23:28",
//     date_upd: "2022-05-28 02:23:28",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>La collection PolyFaune de la marque Studio Design propose des pièces aux coupes basiques et aux visuels colorés inspirés des origamis japonais traditionnels. À porter avec un chino ou un jean. Le procédé d'impression par sublimation garantit la qualité et la longévité des couleurs.</p>",
//     description_short:
//       "<p>Coupe classique, col rond, manches longues. Pull 100% coton avec intérieur brossé pour plus de confort. </p>",
//     link_rewrite: "brown-bear-printed-sweater",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Pull imprimé colibri",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 9,
//     product_attribute_minimal_quantity: "1",
//     id_image: "2-21",
//     legend: "Pull imprimé ours brun",
//     manufacturer_name: "Studio Design",
//     category_default: "Femmes",
//     orderprice: "35.900000",
//     allow_oosp: 0,
//     cover_image_id: "21",
//     category: "femmes",
//     category_name: "Femmes",
//     link: "http://localhost/prestaboutique/femmes/2-brown-bear-printed-sweater.html",
//     attribute_price: 0,
//     price_tax_exc: 28.72,
//     price_without_reduction: 43.08,
//     price_without_reduction_without_tax: 35.9,
//     reduction: 8.616,
//     reduction_without_tax: 7.18,
//     specific_prices: {
//       id_specific_price: "2",
//       id_specific_price_rule: "0",
//       id_cart: "0",
//       id_product: "2",
//       id_shop: "0",
//       id_shop_group: "0",
//       id_currency: "0",
//       id_country: "0",
//       id_group: "0",
//       id_customer: "0",
//       id_product_attribute: "0",
//       price: "-1.000000",
//       from_quantity: "1",
//       reduction: "0.200000",
//       reduction_tax: "1",
//       reduction_type: "percentage",
//       from: "0000-00-00 00:00:00",
//       to: "0000-00-00 00:00:00",
//       score: "32",
//     },
//     quantity_all_versions: 2100,
//     features: [
//       {
//         name: "Composition",
//         value: "Coton",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "Manches longues",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       1: {
//         id_attribute: "1",
//         id_attribute_group: "1",
//         name: "S",
//         group: "Taille",
//         reference: "demo_3",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/21-home_default/brown-bear-printed-sweater.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/21-home_default/brown-bear-printed-sweater.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: true,
//     discount_type: "percentage",
//     discount_percentage: "-20%",
//     discount_percentage_absolute: "20%",
//     discount_amount: "8,62 €",
//     discount_amount_to_display: "-8,62 €",
//     price_amount: 34.46,
//     regular_price_amount: 43.08,
//     regular_price: "43,08 €",
//     discount_to_display: "8,62 €",
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "3",
//     id_supplier: "1",
//     id_manufacturer: "2",
//     id_category_default: "9",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 900,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "34,80 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_6",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "13",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Le meilleur reste à venir ! Faites parler vos murs avec cette affiche encadrée chargée d'optimisme sera du plus bel effet dans un bureau ou un open-space. Cadre en bois peint avec passe-partout integré pour un effet de profondeur.</p>",
//     description_short:
//       "<p>Affiche imprimée sur papier rigide, finition mate et surface lisse.</p>",
//     link_rewrite: "affiche-encadree-the-best-is-yet-to-come",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Affiche encadrée The best is yet to come",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 13,
//     product_attribute_minimal_quantity: "1",
//     id_image: "3-3",
//     legend: "Affiche encadrée The best is yet to come",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Art",
//     orderprice: "29.000000",
//     allow_oosp: 0,
//     cover_image_id: "3",
//     category: "art",
//     category_name: "Art",
//     link: "http://localhost/prestaboutique/art/3-affiche-encadree-the-best-is-yet-to-come.html",
//     attribute_price: 0,
//     price_tax_exc: 29,
//     price_without_reduction: 34.8,
//     price_without_reduction_without_tax: 29,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 1500,
//     features: [
//       {
//         name: "Composition",
//         value: "Papier mat",
//         id_feature: "1",
//         position: "0",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       3: {
//         id_attribute: "19",
//         id_attribute_group: "3",
//         name: "40x60cm",
//         group: "Dimension",
//         reference: "demo_6",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/3-home_default/affiche-encadree-the-best-is-yet-to-come.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/3-home_default/affiche-encadree-the-best-is-yet-to-come.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 34.8,
//     regular_price_amount: 34.8,
//     regular_price: "34,80 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "4",
//     id_supplier: "1",
//     id_manufacturer: "2",
//     id_category_default: "9",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 900,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "34,80 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_5",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "404",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "16",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Le meilleur reste à venir ! Faites parler vos murs avec cette affiche encadrée chargée d'optimisme sera du plus bel effet dans un bureau ou un open-space. Cadre en bois peint avec passe-partout integré pour un effet de profondeur.</p>",
//     description_short:
//       "<p>Affiche imprimée sur papier rigide, finition mate et surface lisse.</p>",
//     link_rewrite: "affiche-encadree-the-adventure-begins",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Affiche encadrée The adventure begins",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 16,
//     product_attribute_minimal_quantity: "1",
//     id_image: "4-4",
//     legend: "Affiche encadrée The adventure begins",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Art",
//     orderprice: "29.000000",
//     allow_oosp: 0,
//     cover_image_id: "4",
//     category: "art",
//     category_name: "Art",
//     link: "http://localhost/prestaboutique/art/4-affiche-encadree-the-adventure-begins.html",
//     attribute_price: 0,
//     price_tax_exc: 29,
//     price_without_reduction: 34.8,
//     price_without_reduction_without_tax: 29,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 1500,
//     features: [
//       {
//         name: "Composition",
//         value: "Papier mat",
//         id_feature: "1",
//         position: "0",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       3: {
//         id_attribute: "19",
//         id_attribute_group: "3",
//         name: "40x60cm",
//         group: "Dimension",
//         reference: "demo_5",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/4-home_default/affiche-encadree-the-adventure-begins.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/4-home_default/affiche-encadree-the-adventure-begins.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 34.8,
//     regular_price_amount: 34.8,
//     regular_price: "34,80 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "5",
//     id_supplier: "1",
//     id_manufacturer: "2",
//     id_category_default: "9",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "34,80 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_7",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "19",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Le meilleur reste à venir ! Faites parler vos murs avec cette affiche encadrée chargée d'optimisme sera du plus bel effet dans un bureau ou un open-space. Cadre en bois peint avec passe-partout integré pour un effet de profondeur.</p>",
//     description_short:
//       "<p>Affiche imprimée sur papier rigide, finition mate et surface lisse.</p>",
//     link_rewrite: "affiche-encadree-today-is-a-good-day",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Affiche encadrée Today is a good day",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 19,
//     product_attribute_minimal_quantity: "1",
//     id_image: "5-5",
//     legend: "Affiche encadrée Today is a good day",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Art",
//     orderprice: "29.000000",
//     allow_oosp: 0,
//     cover_image_id: "5",
//     category: "art",
//     category_name: "Art",
//     link: "http://localhost/prestaboutique/art/5-affiche-encadree-today-is-a-good-day.html",
//     attribute_price: 0,
//     price_tax_exc: 29,
//     price_without_reduction: 34.8,
//     price_without_reduction_without_tax: 29,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 900,
//     features: [
//       {
//         name: "Composition",
//         value: "Papier mat",
//         id_feature: "1",
//         position: "0",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       3: {
//         id_attribute: "19",
//         id_attribute_group: "3",
//         name: "40x60cm",
//         group: "Dimension",
//         reference: "demo_7",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/5-home_default/affiche-encadree-today-is-a-good-day.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/5-home_default/affiche-encadree-today-is-a-good-day.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 34.8,
//     regular_price_amount: 34.8,
//     regular_price: "34,80 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "6",
//     id_supplier: "2",
//     id_manufacturer: "1",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "14,28 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_11",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "standard",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Le meilleur reste à venir ! Commencez la journée avec une pensée positive. Diamètre : 8,2cm / Hauteur : 9,5cm / Poids : 0.43kg. Passe au lave-vaisselle.</p>",
//     description_short: "<p>Mug en céramique blanche, 325ml.</p>",
//     link_rewrite: "mug-the-best-is-yet-to-come",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Mug The best is yet to come",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "6-6",
//     legend: "Mug The best is yet to come",
//     manufacturer_name: "Studio Design",
//     category_default: "Accessoires de maison",
//     orderprice: "11.900000",
//     allow_oosp: 0,
//     cover_image_id: "6",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/6-mug-the-best-is-yet-to-come.html",
//     attribute_price: 0,
//     price_tax_exc: 11.9,
//     price_without_reduction: 14.28,
//     price_without_reduction_without_tax: 11.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 300,
//     features: [
//       {
//         name: "Composition",
//         value: "Céramique",
//         id_feature: "1",
//         position: "0",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/6-home_default/mug-the-best-is-yet-to-come.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/6-home_default/mug-the-best-is-yet-to-come.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 14.28,
//     regular_price_amount: 14.28,
//     regular_price: "14,28 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "7",
//     id_supplier: "2",
//     id_manufacturer: "1",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "14,28 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_12",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "standard",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>L'aventure commence avec une tasse de café. Partez à la conquête de votre journée ! Diamètre : 8,2cm / Hauteur : 9,5cm / Poids : 0.43kg. Passe au lave-vaisselle.</p>",
//     description_short: "<p>Mug en céramique blanche. 325ml</p>",
//     link_rewrite: "mug-the-adventure-begins",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Mug The adventure begins",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "7-7",
//     legend: "Mug The adventure begins",
//     manufacturer_name: "Studio Design",
//     category_default: "Accessoires de maison",
//     orderprice: "11.900000",
//     allow_oosp: 0,
//     cover_image_id: "7",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/7-mug-the-adventure-begins.html",
//     attribute_price: 0,
//     price_tax_exc: 11.9,
//     price_without_reduction: 14.28,
//     price_without_reduction_without_tax: 11.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 300,
//     features: [
//       {
//         name: "Composition",
//         value: "Céramique",
//         id_feature: "1",
//         position: "0",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/7-home_default/mug-the-adventure-begins.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/7-home_default/mug-the-adventure-begins.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 14.28,
//     regular_price_amount: 14.28,
//     regular_price: "14,28 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "8",
//     id_supplier: "2",
//     id_manufacturer: "1",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "14,28 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_13",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "404",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "standard",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Ajoutez un nuage d'optimisme à votre café et démarrez la journée du bon pied, même les jours de réveil difficile ! Diamètre : 8,2cm / Hauteur : 9,5cm / Poids : 0.43kg. Passe au lave-vaisselle.</p>",
//     description_short: "<p>Mug en céramique blanche. 325ml</p>",
//     link_rewrite: "mug-today-is-a-good-day",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Mug Today is a good day",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "8-8",
//     legend: "Mug Today is a good day",
//     manufacturer_name: "Studio Design",
//     category_default: "Accessoires de maison",
//     orderprice: "11.900000",
//     allow_oosp: 0,
//     cover_image_id: "8",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/8-mug-today-is-a-good-day.html",
//     attribute_price: 0,
//     price_tax_exc: 11.9,
//     price_without_reduction: 14.28,
//     price_without_reduction_without_tax: 11.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 300,
//     features: [
//       {
//         name: "Composition",
//         value: "Céramique",
//         id_feature: "1",
//         position: "0",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/8-home_default/mug-today-is-a-good-day.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/8-home_default/mug-today-is-a-good-day.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 14.28,
//     regular_price_amount: 14.28,
//     regular_price: "14,28 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "9",
//     id_supplier: "2",
//     id_manufacturer: "1",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 0,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "22,68 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_15",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-08-01 14:25:39",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Ce coussin imprimé renard ajoutera une touche graphique et colorée à votre canapé, fauteuil ou lit. Optez pour une déco moderne et zen qui invite à la relaxation. Housse 100% coton lavable en machine à 60° / Intérieur 100% polyester hypoallergénique. </p>",
//     description_short:
//       "<p>Coussin déhoussable avec zip invisible au dos. 32x32cm</p>",
//     link_rewrite: "coussin-renard",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Coussin renard",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "9-9",
//     legend: "Coussin renard",
//     manufacturer_name: "Studio Design",
//     category_default: "Accessoires de maison",
//     orderprice: "18.900000",
//     allow_oosp: 0,
//     cover_image_id: "9",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/9-coussin-renard.html",
//     attribute_price: 0,
//     price_tax_exc: 18.9,
//     price_without_reduction: 22.68,
//     price_without_reduction_without_tax: 18.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 0,
//     features: [
//       {
//         name: "Composition",
//         value: "Polyester",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "Housse amovible",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/9-home_default/coussin-renard.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/9-home_default/coussin-renard.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 22.68,
//     regular_price_amount: 22.68,
//     regular_price: "22,68 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_message: "Rupture de stock",
//     availability_date: null,
//     availability: "unavailable",
//   },
//   {
//     id_product: "10",
//     id_supplier: "2",
//     id_manufacturer: "1",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "22,68 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_16",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "24",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Ce coussin imprimé ours brun ajoutera une touche graphique et colorée à votre canapé, fauteuil ou lit. Optez pour une déco moderne et zen qui invite à la relaxation. Housse 100% coton lavable en machine à 60° / Intérieur 100% polyester hypoallergénique. </p>",
//     description_short:
//       "<p>Coussin déhoussable avec zip invisible au dos. 32x32cm</p>",
//     link_rewrite: "coussin-ours-brun",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Coussin ours brun",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 24,
//     product_attribute_minimal_quantity: "1",
//     id_image: "10-11",
//     legend: "Coussin ours brun",
//     manufacturer_name: "Studio Design",
//     category_default: "Accessoires de maison",
//     orderprice: "18.900000",
//     allow_oosp: 0,
//     cover_image_id: "11",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/10-coussin-ours-brun.html",
//     attribute_price: 0,
//     price_tax_exc: 18.9,
//     price_without_reduction: 22.68,
//     price_without_reduction_without_tax: 18.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 600,
//     features: [
//       {
//         name: "Composition",
//         value: "Polyester",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "Housse amovible",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       2: {
//         id_attribute: "8",
//         id_attribute_group: "2",
//         name: "Blanc",
//         group: "Couleur",
//         reference: "demo_16",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/12-home_default/coussin-ours-brun.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/11-home_default/coussin-ours-brun.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 22.68,
//     regular_price_amount: 22.68,
//     regular_price: "22,68 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "11",
//     id_supplier: "2",
//     id_manufacturer: "1",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "22,68 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_17",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "26",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Ce coussin imprimé colibri ajoutera une touche graphique et colorée à votre canapé, fauteuil ou lit. Optez pour une déco moderne et zen qui invite à la relaxation. Housse 100% coton lavable en machine à 60° / Intérieur 100% polyester hypoallergénique. </p>",
//     description_short:
//       "<p>Coussin déhoussable avec zip invisible au dos. 32x32cm</p>",
//     link_rewrite: "coussin-colibri",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Coussin colibri",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 26,
//     product_attribute_minimal_quantity: "1",
//     id_image: "11-13",
//     legend: "Coussin colibri",
//     manufacturer_name: "Studio Design",
//     category_default: "Accessoires de maison",
//     orderprice: "18.900000",
//     allow_oosp: 0,
//     cover_image_id: "13",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/11-coussin-colibri.html",
//     attribute_price: 0,
//     price_tax_exc: 18.9,
//     price_without_reduction: 22.68,
//     price_without_reduction_without_tax: 18.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 600,
//     features: [
//       {
//         name: "Composition",
//         value: "Polyester",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "Housse amovible",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       2: {
//         id_attribute: "8",
//         id_attribute_group: "2",
//         name: "Blanc",
//         group: "Couleur",
//         reference: "demo_17",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/14-home_default/coussin-colibri.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/13-home_default/coussin-colibri.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 22.68,
//     regular_price_amount: 22.68,
//     regular_price: "22,68 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "12",
//     id_supplier: "2",
//     id_manufacturer: "2",
//     id_category_default: "9",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "10,80 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_18",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "1",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "1",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "virtual",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Vous avez un projet créatif d'impression sur-mesure ? L'illustration vectorielle Renard peut être utilisée pour l'impression sur tout support, sans limite de taille. </p>",
//     description_short:
//       "<p>Image vectorielle au format .svg. Téléchargement en vue d'une utilisation privée, personnelle et non commerciale. </p>",
//     link_rewrite: "illustration-vectorielle-renard",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Illustration vectorielle Renard",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "12-15",
//     legend: "Illustration vectorielle Renard",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Art",
//     orderprice: "9.000000",
//     allow_oosp: 1,
//     cover_image_id: "15",
//     category: "art",
//     category_name: "Art",
//     link: "http://localhost/prestaboutique/art/12-illustration-vectorielle-renard.html",
//     attribute_price: 0,
//     price_tax_exc: 9,
//     price_without_reduction: 10.8,
//     price_without_reduction_without_tax: 9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 300,
//     features: [],
//     attachments: [],
//     virtual: 1,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/15-home_default/illustration-vectorielle-renard.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/15-home_default/illustration-vectorielle-renard.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 10.8,
//     regular_price_amount: 10.8,
//     regular_price: "10,80 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "13",
//     id_supplier: "2",
//     id_manufacturer: "2",
//     id_category_default: "9",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "10,80 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_19",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "1",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "1",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "virtual",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Vous avez un projet créatif d'impression sur-mesure ou sur un support particulier ? L'illustration vectorielle Ours brun peut être utilisée pour l'impression sur tout support, sans limite de taille. </p>",
//     description_short:
//       "<p>Image vectorielle au format .svg. Téléchargement en vue d'une utilisation privée, personnelle et non commerciale. </p>",
//     link_rewrite: "illustration-vectorielle-ours-brun",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Illustration vectorielle Ours brun",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "13-16",
//     legend: "Illustration vectorielle Ours brun",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Art",
//     orderprice: "9.000000",
//     allow_oosp: 1,
//     cover_image_id: "16",
//     category: "art",
//     category_name: "Art",
//     link: "http://localhost/prestaboutique/art/13-illustration-vectorielle-ours-brun.html",
//     attribute_price: 0,
//     price_tax_exc: 9,
//     price_without_reduction: 10.8,
//     price_without_reduction_without_tax: 9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 300,
//     features: [],
//     attachments: [],
//     virtual: 1,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/16-home_default/illustration-vectorielle-ours-brun.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/16-home_default/illustration-vectorielle-ours-brun.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 10.8,
//     regular_price_amount: 10.8,
//     regular_price: "10,80 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "14",
//     id_supplier: "2",
//     id_manufacturer: "2",
//     id_category_default: "9",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "10,80 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_20",
//     supplier_reference: "demo_20",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "1",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "1",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-07-16 19:12:22",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "virtual",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Vous avez un projet créatif d'impression sur-mesure ou sur un support particulier ? L'illustration vectorielle Colibri peut être utilisée pour l'impression sur tout support, sans limite de taille. </p>",
//     description_short:
//       "<p>Image vectorielle au format .svg. Téléchargement en vue d'une utilisation privée, personnelle et non commerciale. </p>",
//     link_rewrite: "illustration-vectorielle-colibri",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Illustration vectorielle Colibri",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "14-17",
//     legend: "Illustration vectorielle Colibri",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Art",
//     orderprice: "9.000000",
//     allow_oosp: 1,
//     cover_image_id: "17",
//     category: "art",
//     category_name: "Art",
//     link: "http://localhost/prestaboutique/art/14-illustration-vectorielle-colibri.html",
//     attribute_price: 0,
//     price_tax_exc: 9,
//     price_without_reduction: 10.8,
//     price_without_reduction_without_tax: 9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 300,
//     features: [],
//     attachments: [],
//     virtual: 1,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/17-home_default/illustration-vectorielle-colibri.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/17-home_default/illustration-vectorielle-colibri.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 10.8,
//     regular_price_amount: 10.8,
//     regular_price: "10,80 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "15",
//     id_supplier: "2",
//     id_manufacturer: "0",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 100,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "42,00 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_21",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "1",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "pack",
//     id_shop: "1",
//     id_lang: "1",
//     description: "",
//     description_short:
//       "<p>Mug The Adventure Begins + Affiche encadrée Today is a good day 40x60cm </p>",
//     link_rewrite: "pack-mug-affiche-encadree",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Pack Mug + Affiche encadrée",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "15-23",
//     legend: "Pack Mug + Affiche encadrée",
//     manufacturer_name: null,
//     category_default: "Accessoires de maison",
//     orderprice: "35.000000",
//     allow_oosp: 0,
//     cover_image_id: "23",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/15-pack-mug-affiche-encadree.html",
//     attribute_price: 0,
//     price_tax_exc: 35,
//     price_without_reduction: 42,
//     price_without_reduction_without_tax: 35,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 100,
//     features: [],
//     attachments: [],
//     virtual: 0,
//     pack: 1,
//     packItems: [
//       {
//         id_product: "5",
//         id_supplier: "1",
//         id_manufacturer: "2",
//         id_category_default: "9",
//         id_shop_default: "1",
//         id_tax_rules_group: "1",
//         on_sale: "0",
//         online_only: "0",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//         ecotax: "0.000000",
//         quantity: "0",
//         minimal_quantity: "1",
//         low_stock_threshold: null,
//         low_stock_alert: "0",
//         price: "29.000000",
//         wholesale_price: "0.000000",
//         unity: "",
//         unit_price_ratio: "0.000000",
//         additional_shipping_cost: "0.000000",
//         reference: "demo_7",
//         supplier_reference: "",
//         location: "",
//         width: "0.000000",
//         height: "0.000000",
//         depth: "0.000000",
//         weight: "0.300000",
//         out_of_stock: "2",
//         additional_delivery_times: "1",
//         quantity_discount: "0",
//         customizable: "0",
//         uploadable_files: "0",
//         text_fields: "0",
//         active: "1",
//         redirect_type: "301-category",
//         id_type_redirected: "0",
//         available_for_order: "1",
//         available_date: "0000-00-00",
//         show_condition: "0",
//         condition: "new",
//         show_price: "1",
//         indexed: "1",
//         visibility: "both",
//         cache_is_pack: "0",
//         cache_has_attachments: "0",
//         is_virtual: "0",
//         cache_default_attribute: "19",
//         date_add: "2022-05-28 02:23:29",
//         date_upd: "2022-05-28 02:23:29",
//         advanced_stock_management: "0",
//         pack_stock_type: "3",
//         state: "1",
//         product_type: "combinations",
//         id_shop: "1",
//         id_lang: "1",
//         description:
//           "<p>Le meilleur reste à venir ! Faites parler vos murs avec cette affiche encadrée chargée d'optimisme sera du plus bel effet dans un bureau ou un open-space. Cadre en bois peint avec passe-partout integré pour un effet de profondeur.</p>",
//         description_short:
//           "<p>Affiche imprimée sur papier rigide, finition mate et surface lisse.</p>",
//         link_rewrite: "affiche-encadree-today-is-a-good-day",
//         meta_description: "",
//         meta_keywords: "",
//         meta_title: "",
//         name: "Affiche encadrée Today is a good day\n Dimension-40x60cm",
//         available_now: "",
//         available_later: "",
//         delivery_in_stock: "",
//         delivery_out_stock: "",
//         id_image: "5",
//         legend: "Affiche encadrée Today is a good day",
//         category_default: "Art",
//         pack_quantity: "5",
//         id_product_pack: "15",
//         id_product_attribute_item: "19",
//         id_product_attribute: "19",
//         rate: 20,
//         tax_name: "TVA FR 20%",
//       },
//       {
//         id_product: "7",
//         id_supplier: "2",
//         id_manufacturer: "1",
//         id_category_default: "8",
//         id_shop_default: "1",
//         id_tax_rules_group: "1",
//         on_sale: "0",
//         online_only: "0",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//         ecotax: "0.000000",
//         quantity: "0",
//         minimal_quantity: "1",
//         low_stock_threshold: null,
//         low_stock_alert: "0",
//         price: "11.900000",
//         wholesale_price: "0.000000",
//         unity: "",
//         unit_price_ratio: "0.000000",
//         additional_shipping_cost: "0.000000",
//         reference: "demo_12",
//         supplier_reference: "",
//         location: "",
//         width: "0.000000",
//         height: "0.000000",
//         depth: "0.000000",
//         weight: "0.300000",
//         out_of_stock: "2",
//         additional_delivery_times: "1",
//         quantity_discount: "0",
//         customizable: "0",
//         uploadable_files: "0",
//         text_fields: "0",
//         active: "1",
//         redirect_type: "301-category",
//         id_type_redirected: "0",
//         available_for_order: "1",
//         available_date: "0000-00-00",
//         show_condition: "0",
//         condition: "new",
//         show_price: "1",
//         indexed: "1",
//         visibility: "both",
//         cache_is_pack: "0",
//         cache_has_attachments: "0",
//         is_virtual: "0",
//         cache_default_attribute: "0",
//         date_add: "2022-05-28 02:23:29",
//         date_upd: "2022-05-28 02:23:29",
//         advanced_stock_management: "0",
//         pack_stock_type: "3",
//         state: "1",
//         product_type: "standard",
//         id_shop: "1",
//         id_lang: "1",
//         description:
//           "<p>L'aventure commence avec une tasse de café. Partez à la conquête de votre journée ! Diamètre : 8,2cm / Hauteur : 9,5cm / Poids : 0.43kg. Passe au lave-vaisselle.</p>",
//         description_short: "<p>Mug en céramique blanche. 325ml</p>",
//         link_rewrite: "mug-the-adventure-begins",
//         meta_description: "",
//         meta_keywords: "",
//         meta_title: "",
//         name: "Mug The adventure begins",
//         available_now: "",
//         available_later: "",
//         delivery_in_stock: "",
//         delivery_out_stock: "",
//         id_image: "7",
//         legend: "Mug The adventure begins",
//         category_default: "Accessoires de maison",
//         pack_quantity: "5",
//         id_product_pack: "15",
//         id_product_attribute_item: "0",
//         rate: 20,
//         tax_name: "TVA FR 20%",
//       },
//     ],
//     nopackprice: 245.39999999999998,
//     customization_required: false,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/23-home_default/pack-mug-affiche-encadree.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/23-home_default/pack-mug-affiche-encadree.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 42,
//     regular_price_amount: 42,
//     regular_price: "42,00 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "16",
//     id_supplier: "2",
//     id_manufacturer: "2",
//     id_category_default: "7",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "15,48 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_8",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "28",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Le carnet de notes Renard est idéal pour consigner vos idées les plus ingénieuses. En voyage, au bureau ou à la maison, sa qualité de fabrication et son design attachant vous donneront l'envie d'écrire ! Papier 90g/m2, reliure double spirale.</p>",
//     description_short:
//       "<p>Carnet 120 pages avec couverture rigide en carton recyclé. 16x22cm</p>",
//     link_rewrite: "carnet-de-notes-renard",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Carnet de notes Renard",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 28,
//     product_attribute_minimal_quantity: "1",
//     id_image: "16-18",
//     legend: "Carnet de notes Renard",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Papeterie",
//     orderprice: "12.900000",
//     allow_oosp: 0,
//     cover_image_id: "18",
//     category: "papeterie",
//     category_name: "Papeterie",
//     link: "http://localhost/prestaboutique/papeterie/16-carnet-de-notes-renard.html",
//     attribute_price: 0,
//     price_tax_exc: 12.9,
//     price_without_reduction: 15.48,
//     price_without_reduction_without_tax: 12.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 1200,
//     features: [
//       {
//         name: "Composition",
//         value: "Carton recyclé",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "120 pages",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       4: {
//         id_attribute: "22",
//         id_attribute_group: "4",
//         name: "Ligné",
//         group: "Type de papier",
//         reference: "demo_8",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/18-home_default/carnet-de-notes-renard.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/18-home_default/carnet-de-notes-renard.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 15.48,
//     regular_price_amount: 15.48,
//     regular_price: "15,48 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "17",
//     id_supplier: "2",
//     id_manufacturer: "2",
//     id_category_default: "7",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "15,48 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_9",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "32",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Le carnet de notes Renard est idéal pour consigner vos idées les plus ingénieuses. En voyage, au bureau ou à la maison, sa qualité de fabrication et son design attachant vous donneront l'envie d'écrire ! Papier 90g/m2, reliure double spirale.</p>",
//     description_short:
//       "<p>Carnet 120 pages avec couverture rigide en carton recyclé. 16x22cm</p>",
//     link_rewrite: "carnet-de-notes-ours-brun",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Carnet de notes Ours brun",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 32,
//     product_attribute_minimal_quantity: "1",
//     id_image: "17-19",
//     legend: "Carnet de notes Renard",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Papeterie",
//     orderprice: "12.900000",
//     allow_oosp: 0,
//     cover_image_id: "19",
//     category: "papeterie",
//     category_name: "Papeterie",
//     link: "http://localhost/prestaboutique/papeterie/17-carnet-de-notes-ours-brun.html",
//     attribute_price: 0,
//     price_tax_exc: 12.9,
//     price_without_reduction: 15.48,
//     price_without_reduction_without_tax: 12.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 1200,
//     features: [
//       {
//         name: "Composition",
//         value: "Carton recyclé",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "120 pages",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       4: {
//         id_attribute: "22",
//         id_attribute_group: "4",
//         name: "Ligné",
//         group: "Type de papier",
//         reference: "demo_9",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/19-home_default/carnet-de-notes-ours-brun.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/19-home_default/carnet-de-notes-ours-brun.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 15.48,
//     regular_price_amount: 15.48,
//     regular_price: "15,48 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "18",
//     id_supplier: "2",
//     id_manufacturer: "2",
//     id_category_default: "7",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "15,48 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_10",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "0",
//     uploadable_files: "0",
//     text_fields: "0",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: null,
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "36",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "combinations",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Le carnet de notes Renard est idéal pour consigner vos idées les plus ingénieuses. En voyage, au bureau ou à la maison, sa qualité de fabrication et son design attachant vous donneront l'envie d'écrire ! Papier 90g/m2, reliure double spirale.</p>",
//     description_short:
//       "<p>Carnet 120 pages avec couverture rigide en carton recyclé. 16x22cm</p>",
//     link_rewrite: "carnet-de-notes-colibri",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Carnet de notes Colibri",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: 36,
//     product_attribute_minimal_quantity: "1",
//     id_image: "18-20",
//     legend: "Carnet de notes Renard",
//     manufacturer_name: "Graphic Corner",
//     category_default: "Papeterie",
//     orderprice: "12.900000",
//     allow_oosp: 0,
//     cover_image_id: "20",
//     category: "papeterie",
//     category_name: "Papeterie",
//     link: "http://localhost/prestaboutique/papeterie/18-carnet-de-notes-colibri.html",
//     attribute_price: 0,
//     price_tax_exc: 12.9,
//     price_without_reduction: 15.48,
//     price_without_reduction_without_tax: 12.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 1200,
//     features: [
//       {
//         name: "Composition",
//         value: "Carton recyclé",
//         id_feature: "1",
//         position: "0",
//       },
//       {
//         name: "Propriété",
//         value: "120 pages",
//         id_feature: "2",
//         position: "1",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: false,
//     attributes: {
//       4: {
//         id_attribute: "22",
//         id_attribute_group: "4",
//         name: "Ligné",
//         group: "Type de papier",
//         reference: "demo_10",
//         ean13: "",
//         isbn: "",
//         upc: "",
//         mpn: "",
//       },
//     },
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/20-home_default/carnet-de-notes-colibri.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/20-home_default/carnet-de-notes-colibri.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 15.48,
//     regular_price_amount: 15.48,
//     regular_price: "15,48 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
//   {
//     id_product: "19",
//     id_supplier: "2",
//     id_manufacturer: "1",
//     id_category_default: "8",
//     id_shop_default: "1",
//     id_tax_rules_group: "1",
//     on_sale: "0",
//     online_only: "0",
//     ean13: "",
//     isbn: "",
//     upc: "",
//     mpn: "",
//     ecotax: "0.000000",
//     quantity: 300,
//     minimal_quantity: "1",
//     low_stock_threshold: null,
//     low_stock_alert: "0",
//     price: "16,68 €",
//     wholesale_price: "0.000000",
//     unity: "",
//     unit_price_ratio: "0.000000",
//     additional_shipping_cost: "0.000000",
//     reference: "demo_14",
//     supplier_reference: "",
//     location: "",
//     width: "0.000000",
//     height: "0.000000",
//     depth: "0.000000",
//     weight: "0.300000",
//     out_of_stock: "2",
//     additional_delivery_times: "1",
//     quantity_discount: "0",
//     customizable: "1",
//     uploadable_files: "0",
//     text_fields: "1",
//     active: "1",
//     redirect_type: "301-category",
//     id_type_redirected: "0",
//     available_for_order: "1",
//     available_date: "0000-00-00",
//     show_condition: "0",
//     condition: "new",
//     show_price: "1",
//     indexed: "1",
//     visibility: "both",
//     cache_is_pack: "0",
//     cache_has_attachments: "0",
//     is_virtual: "0",
//     cache_default_attribute: "0",
//     date_add: "2022-05-28 02:23:29",
//     date_upd: "2022-05-28 02:23:29",
//     advanced_stock_management: "0",
//     pack_stock_type: "3",
//     state: "1",
//     product_type: "standard",
//     id_shop: "1",
//     id_lang: "1",
//     description:
//       "<p>Personnalisez votre mug avec le texte de votre choix. Une humeur, un message, une citation... À vous de choisir ! Nombre maximum de caractères : --- Diamètre : 8,2cm / Hauteur : 9,5cm / Poids : 0.43kg. Passe au lave-vaisselle.</p>",
//     description_short: "<p>Mug en céramique blanche. 325ml</p>",
//     link_rewrite: "customizable-mug",
//     meta_description: "",
//     meta_keywords: "",
//     meta_title: "",
//     name: "Mug personnalisable",
//     available_now: "",
//     available_later: "",
//     delivery_in_stock: "",
//     delivery_out_stock: "",
//     new: "0",
//     id_product_attribute: "0",
//     product_attribute_minimal_quantity: null,
//     id_image: "19-22",
//     legend: "Customizable mug",
//     manufacturer_name: "Studio Design",
//     category_default: "Accessoires de maison",
//     orderprice: "13.900000",
//     allow_oosp: 0,
//     cover_image_id: "22",
//     category: "accessoires-de-maison",
//     category_name: "Accessoires de maison",
//     link: "http://localhost/prestaboutique/accessoires-de-maison/19-customizable-mug.html",
//     attribute_price: 0,
//     price_tax_exc: 13.9,
//     price_without_reduction: 16.68,
//     price_without_reduction_without_tax: 13.9,
//     reduction: 0,
//     reduction_without_tax: 0,
//     specific_prices: [],
//     quantity_all_versions: 300,
//     features: [
//       {
//         name: "Composition",
//         value: "Céramique",
//         id_feature: "1",
//         position: "0",
//       },
//     ],
//     attachments: [],
//     virtual: 0,
//     pack: 0,
//     packItems: [],
//     nopackprice: 0,
//     customization_required: true,
//     rate: 20,
//     tax_name: "TVA FR 20%",
//     ecotax_rate: 0,
//     unit_price: "",
//     default_image: {
//       url: "http://localhost/prestaboutique/22-home_default/customizable-mug.jpg",
//       width: 250,
//       height: 250,
//     },
//     cover: {
//       url: "http://localhost/prestaboutique/22-home_default/customizable-mug.jpg",
//       width: 250,
//       height: 250,
//     },
//     has_discount: false,
//     discount_type: null,
//     discount_percentage: null,
//     discount_percentage_absolute: null,
//     discount_amount: null,
//     discount_amount_to_display: null,
//     price_amount: 16.68,
//     regular_price_amount: 16.68,
//     regular_price: "16,68 €",
//     discount_to_display: null,
//     unit_price_full: "",
//     show_availability: true,
//     availability_date: null,
//     availability_message: "",
//     availability: "available",
//   },
// ];

function Products({ productsList }) {
  const [products, setProducts] = useState(productsList);
  const [openCart, setOpenCart] = useState(false);

  const addProduct = (product) => {
    // add to prestashop cart
    // console.log(
    //   selectedProducts.filter((prod) => prod.id === product.id).length
    // );
    // if (selectedProducts.filter((prod) => prod.id === product.id).length != 0) {
    //   //selectedProducts.filter((prod) => prod.id !== product.id);
    //   setSelectedProducts([product, ...selectedProducts]);
    //   console.log("kayn");
    // }
  };

  return (
    <div className="py-5">
      <CoverThumbnails />
      <ProductList products={products} addProduct={addProduct} />
      {openCart && <Cart open={openCart} close={() => setOpenCart(false)} />}
      <BottomCart
        passerCommande={() => {
          setOpenCart(true);
        }}
      />
    </div>
  );
}

export default Products;

export async function getServerSideProps(context) {
  var requestOptions = {
    method: "GET",
  };

  const url = Urls.productList;

  const result = await fetch(url, requestOptions)
    .then((response) => response?.json())
    .then((result) => {
      return result;
    })
    .catch((error) => console.log("error", error));

  return {
    props: { productsList: result?.psdata ? result?.psdata : [] }, // will be passed to the page component as props
  };
}
